# Generated by Django 5.0.6 on 2024-05-31 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('assign_date', models.DateField(default=datetime.date.today)),
                ('is_complete', models.BooleanField()),
            ],
        ),
    ]
